name: CI Pipeline

on:
  push:
    paths:              # Trigger when source code, sln or prj files, this file, or the xunit config file is changed.
      - '**/*.cs'
      - '**/*.sln'
      - '**/*.csproj'
      - '**/ci.yaml'
      - '**/xunit.runner.json'
    branches:
      - main
      - '**release**'   # Trigger on branches with 'release' in the name
  pull_request:
    paths:              # Trigger when source code, sln or prj files, this file, or the xunit config file is changed.
      - '**/*.cs'
      - '**/*.sln'
      - '**/*.csproj'
      - '**/ci.yaml'
      - '**/xunit.runner.json'
    branches:
      - main
      - '**release**'   # Trigger on branches with 'release' in the name

jobs:
  build-and-test:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x' # Adjust to your target .NET version

      # Uncomment this process if you want the windows build to take 3mins extra but get rid of the 'Workload updates are available. Run `dotnet workload list` for more information' msg after building
      #- name: Update dotnet workloads (Windows)
      #  if: matrix.os == 'windows-latest'
      #  run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore tests/EStimLibrary.UnitTests/EStimLibrary.UnitTests.sln

      - name: Build solution without restore
      #  if: matrix.os != 'windows-latest'
        run: dotnet build tests/EStimLibrary.UnitTests/EStimLibrary.UnitTests.sln --no-restore --configuration Release

      #- name: Build solution with restore (Windows)
      #  if: matrix.os == 'windows-latest'
      #  run: dotnet build tests/EStimLibrary.UnitTests/EStimLibrary.UnitTests.sln --configuration Release

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Run unit tests and collect coverage
        run: dotnet test tests/EStimLibrary.UnitTests/EStimLibrary.UnitTests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Generate coverage report
        run: |
          reportgenerator -reports:tests/**/coverage.cobertura.xml -targetdir:coverage -reporttypes:Html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.os }}  # Append OS suffix to artifact name
          path: coverage

